# 변수 정의

In [2]:
a=1; print(type(a))

<class 'int'>


In [3]:
a=1; a=float(a); print(type(a))

<class 'float'>


In [4]:
a=1.2; a=int(a); print(type(a))

<class 'int'>


In [5]:
a='123'; print(type(a)); print(a[1])

<class 'str'>
2


In [6]:
a='123' ; a=list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [7]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


In [8]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


##### variable dictionary, have to use { }, unlike list

In [9]:
a = {"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [10]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [11]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [12]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


In [13]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>
